use_frameworks!

target 'MDGroupAvatarView_Example' do
    use_frameworks!
    pod 'MDGroupAvatarView', :git => 'https://github.com/ttmdung203/MDGroupAvatarView.git'

  target 'MDGroupAvatarView_Tests' do
    inherit! :search_paths

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end

