use_frameworks!

target 'MDGroupAvatarView_Example' do
    use_frameworks!
    pod 'MDGroupAvatarView', :path => '..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
